"""Application-wide constants and enumerations."""

# Intent Categories
INTENT_ACCOUNT = "ACCOUNT"
INTENT_BILLING = "BILLING"
INTENT_PRICING = "PRICING"
INTENT_REFUND = "REFUND"
INTENT_SUBSCRIPTION = "SUBSCRIPTION"
INTENT_TECHNICAL_SUPPORT = "TECHNICAL_SUPPORT"
INTENT_GENERAL_SUPPORT = "GENERAL_SUPPORT"

# List of all valid intents for training/validation
VALID_INTENTS = [
    INTENT_ACCOUNT,
    INTENT_BILLING,
    INTENT_PRICING,
    INTENT_REFUND,
    INTENT_SUBSCRIPTION,
    INTENT_TECHNICAL_SUPPORT,
    INTENT_GENERAL_SUPPORT,
]

# Fallback Reason Codes
FALLBACK_REASON_LOW_CLASSIFICATION_CONFIDENCE = "LOW_CLASSIFICATION_CONFIDENCE"
FALLBACK_REASON_NO_RELEVANT_KNOWLEDGE = "NO_RELEVANT_KNOWLEDGE"
FALLBACK_REASON_LOW_RETRIEVAL_CONFIDENCE = "LOW_RETRIEVAL_CONFIDENCE"
FALLBACK_REASON_LLM_INSUFFICIENT_INFORMATION = "LLM_INSUFFICIENT_INFORMATION"

# Internal LLM Signal
INSUFFICIENT_INFORMATION_SIGNAL = "INSUFFICIENT_INFORMATION"

# Default Fallback Message
DEFAULT_FALLBACK_MESSAGE = "I don't have enough information to answer that accurately. Please contact our support team for further assistance."
